name: Node Ok

on:
  push:
    branches:
    - master

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        env:
          KEY: "${{ secrets.KEY }}"
      - run: |
          touch .env
          echo KEY="${{ secrets.KEY }}" >> .env
          node index.js
